/**
 * @enum ROUTE_NAME
 */
export enum ROUTE_NAME {
  AUTH_LOGIN = 'AUTH.LOGIN',
  BOOKING_HOME = 'BOOKING.HOME',
  BOOKING_BOOKINGS = 'BOOKING.BOOKINGS',
  BOOKING_REPORT = 'BOOKING.REPORT',
  BOOKING_ROOMS = 'BOOKING.ROOMS',

  TASKS_HOME = 'TASKS.HOME',
}
